site_name: Gestión de Bases de Datos
docs_dir: docs
site_dir: site
use_directory_urls: false
theme:
  name: material
  favicon: assets/images/fa-database.svg
  icon:
    logo: fontawesome/solid/database
  features:
    - navigation.sections
    - navigation.expand
  palette:
    - scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/weather-night
        name: Cambiar a modo oscuro
    - scheme: slate
      primary: cyan
      accent: lime
      toggle:
        icon: material/weather-sunny
        name: Cambiar a modo claro
plugins:
- search
nav:
- Inicio: index.md
- Entorno: 00entorno.md
- "1.- Sistemas de almacenamiento": 01intro.md
- "2.- Diseño conceptual: Modelo Entidad/Relación. EER Extendido": 02er.md
- "3.- Diseño lógico: Modelo Relacional. Normalización": 03mr.md
- "4.- Diseño lógico: Transformación de ER a MR": 04mr-eer.md
- "5.- Diseño físico: DDL y DML": 05ddl.md
- "6.- Consultas sencillas. Funciones. Joins": 06sql.md
- "7.- Consultas agregadas. Funciones ventana. Vistas": 07sql-group.md
- "8.- Subconsultas. Optimización. CTE. Índices": 08sql-subquerys.md
- "9.- DCL y TCL. Usuarios, permisos y transacciones": 09dcl-tcl.md
- "10.- Programación SQL. Procedimientos y funciones": 10plsql.md
- "11.- PL/SQL Avanzado. Eventos, disparadores y cursores": 11triggers.md
- "12.- NoSQL y Big Data":
  - "12.1.- Fundamentos NoSQL": 12nosql.md
  - "12.2.- Redis": 12redis.md
- "13.- MongoDB": 13mongodb.md
- Anexos:
  - Consultas geoespaciales sobre MariaDB: anexos/geoespaciales.md
  - Consultas jerárquicas: anexos/jerarquicas.md
  - El tipo de datos JSON en SQL: anexos/json.md
  - Restricciones en las relaciones: anexos/restricciones-relaciones.md
  - Supuestos completos: anexos/supuestos.md
  - Relaciones ternarias en el modelo conceptual: anexos/ternarias.md
- Validación CE: validacion.md
- Relación con otros módulos profesionales: relacion.md
- Autoevaluación: satisfaccion.md
- Vocabulari: vocabulari.md
- Tags: tags.md
